# Generated by Django 3.2.13 on 2022-06-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe_bug', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='complain',
            name='person',
            field=models.CharField(default='Anonymorse', max_length=15),
        ),
    ]
