# Generated by Django 3.2.13 on 2022-06-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0004_alter_complain_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='title',
            field=models.CharField(choices=[('Harasment', 'Harasment'), ('Finacial', 'Finacial'), ('Environmental', 'Environmental')], max_length=40),
        ),
    ]
