# Generated by Django 3.2.13 on 2022-06-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0005_alter_complain_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='person',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='complain',
            name='title',
            field=models.CharField(choices=[('Harasment', 'Sexual Harasment'), ('Cultism', 'Cultism'), ('Finacial', 'Finacial'), ('Dressing', 'Indicent Dressing'), ('School Environment', 'School Environment')], max_length=40),
        ),
    ]
